const strings = {
  appName: '每日反思',
  aiName: '回响',
  tabHome: '今天',
  tabHistory: '历史',
  noEntryToday: '今天还没有记录',
  noEntryHint: '写下今天的第一条想法吧',
  textPlaceholder: '记录你此刻的想法...',
  addNote: '记录新想法',
  submitNote: '开始反思',
  submitting: '提交中...',
  summarize: '生成今日总结',
  summarizing: '正在生成总结...',
  noSummary: '还没有总结，点击按钮让回响帮你回顾今天',
  discussionPlaceholder: '和回响聊聊你的想法...',
  send: '发送',
  regenerate: '重新生成',
  delete: '删除',
  deleteConfirm: '确定要删除这条笔记吗？',
  cancel: '取消',
  confirm: '确定',
  loading: '加载中...',
  errorGeneral: '出了点问题',
  errorRetry: '重试',
  offline: '当前离线，无法提交新笔记',
  emptyHistory: '还没有记录，去写一条吧',
  notesSection: '原始笔记',
  summarySection: '今日总结',
  discussionSection: '深度讨论',
  imageAlt: '笔记图片',
  addImage: '添加图片',
  back: '返回',
  keywords: '关键词',
  extractKeywords: '提取关键词',
  extractingKeywords: '正在提取...',
  noKeywords: '还没有关键词',
  selectExport: '选择导出',
  cancelSelect: '取消选择',
  exportToObsidian: '导出到 Obsidian',
  exporting: '正在导出...',
  exportSuccess: '成功导出 {count} 篇',
  exportPartial: '成功导出 {exported} 篇，{failed} 篇失败',
  exportFail: '导出失败',
  noSelection: '请先选择要导出的日期',
  exportPathTitle: '导出到 Obsidian',
  exportPathLabel: '目标路径',
  exportPathPlaceholder: '输入 Obsidian vault 路径...',
  exportPathHint: 'Markdown 文件将保存到此路径，图片保存到 attachments/ 子目录',
  obsidianNotConfigured: '请先在 .env 中配置 OBSIDIAN_VAULT_PATH，或在下方输入目标路径',
  browse: '浏览...',
};

export default strings;
